BACK_FILES:=Claim.go ClaimBase.go Crossing.go DaytimeClaim.go Direction.go Lane.go main.go
GOBUILD=go build -o $@ $^

#

back : $(DST)/traffic-lights

$(DST)/traffic-lights : $(foreach f,$(BACK_FILES),$(SRC)/back/$(f))
	$(GOBUILD)

test :
	go test $(SRC)/back/*.go

#

front :
	rm --recursive --force $(DST)/static
	cp --archive $(SRC)/static $(DST)/static

#

all : back front
