BACK_FILES:=Browser.go Claim.go ClaimBase.go Command.go Crossing.go DaytimeClaim.go Direction.go Http.go Lane.go Report.go main.go
GOBUILD=go build -o $@

#

back : $(DST)/traffic-lights

$(DST)/traffic-lights : $(foreach f,$(BACK_FILES),$(SRC)/back/$(f))
	cd $(SRC)/back && $(GOBUILD)

test :
	cd $(SRC)/back && go test

#

front :
	rm --recursive --force $(DST)/front
	cp --archive $(SRC)/front $(DST)/front

#

all : back front
