FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y git
RUN apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
RUN apt install -y python3
RUN apt install -y ninja-build
